name: CI

on:
  push:
    branches:
      - '**'
  pull_request:

permissions:
  contents: read

jobs:
  vscode:
    uses: ./.github/workflows/vscode-validation.yml
    permissions:
      contents: read
